//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huella
    {
        public int idHuella { get; set; }
        public byte[] huella1 { get; set; }
        public bool activo { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int idPersonal { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
