//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visita()
        {
            this.ingresoSalidaVisita = new HashSet<ingresoSalidaVisita>();
            this.UsuarioVisita = new HashSet<UsuarioVisita>();
        }
    
        public int idVisita { get; set; }
        public int idTipoVisita { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string placas { get; set; }
        public string fotoUrl { get; set; }
        public int idUbicacion { get; set; }
        public Nullable<bool> activo { get; set; }
        public string QR { get; set; }
    
        public virtual TipoVisita TipoVisita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingresoSalidaVisita> ingresoSalidaVisita { get; set; }
        public virtual SolicitudAcceso SolicitudAcceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioVisita> UsuarioVisita { get; set; }
    }
}
