//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        public int idDispositivo { get; set; }
        public string Ip { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public int idUbicacion { get; set; }
        public bool activo { get; set; }
        public string puerto { get; set; }
        public string tipoDispositivo { get; set; }
        public string protocolo { get; set; }
    
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
