//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAcceso
    {
        public int idVisita { get; set; }
        public Nullable<int> idUbicacion { get; set; }
        public Nullable<int> idUsuarioConcedeAcceso { get; set; }
        public Nullable<int> idUsuarioCancelaAcceso { get; set; }
        public Nullable<System.DateTime> fechaRespuesta { get; set; }
    
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Visita Visita { get; set; }
    }
}
